name: torch-gpu-clip
channels:
  - pytorch
dependencies:
  - python >= 3.8
  - pip
  - pytorch
  - torchvision
  - ftfy
  - regex
  - tqdm
  - git
  - nltk
  - cma
  - pytorch-pretrained-biggan
  - imageio
  - pip:
    - git+https://github.com/openai/CLIP.git
