name: torch-gpu-clip
channels:
  - pytorch
dependencies:
  - python >= 3.8
  - pip
  - pytorch==1.7.1
  - torchvision==0.8.2
  - torchaudio==0.7.2
  - cudatoolkit=10.1
  - ftfy
  - regex
  - tqdm
  - git
  - nltk
  - cma
  - imageio
  - ipykernel
  - scipy
  - pip:
    - git+https://github.com/openai/CLIP.git
    - pytorch-pretrained-biggan
